name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Get current version
      id: current_version
      run: |
        VERSION=$(ruby -r './lib/ruby_todo/version' -e 'puts RubyTodo::VERSION')
        echo "Current version: $VERSION"
        echo "current_version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Increment patch version
      id: next_version
      run: |
        CURRENT_VERSION=${{ steps.current_version.outputs.current_version }}
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        echo "New version: $NEW_VERSION"
        echo "next_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Update version.rb
      run: |
        NEW_VERSION=${{ steps.next_version.outputs.next_version }}
        sed -i "s/VERSION = \"${{ steps.current_version.outputs.current_version }}\"/VERSION = \"$NEW_VERSION\"/" lib/ruby_todo/version.rb
    
    - name: Update CHANGELOG.md
      run: |
        NEW_VERSION=${{ steps.next_version.outputs.next_version }}
        DATE=$(date +%Y-%m-%d)
        sed -i "1i ## [$NEW_VERSION] - $DATE\n\n* Auto-release from CI\n\n" CHANGELOG.md
    
    - name: Run tests
      run: bundle exec rake test
      
    - name: Commit version bump
      run: |
        NEW_VERSION=${{ steps.next_version.outputs.next_version }}
        git add lib/ruby_todo/version.rb CHANGELOG.md
        git commit -m "Bump version to $NEW_VERSION [ci skip]"
        git tag v$NEW_VERSION
        git push
        git push --tags
    
    - name: Build gem
      run: bundle exec rake build
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.next_version.outputs.next_version }}
        name: Release v${{ steps.next_version.outputs.next_version }}
        generate_release_notes: true
        files: pkg/ruby_todo-${{ steps.next_version.outputs.next_version }}.gem
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish to RubyGems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir -p ~/.gem
        echo "---" > ~/.gem/credentials
        echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" >> ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem push pkg/ruby_todo-${{ steps.next_version.outputs.next_version }}.gem 